CSHARP/OENIK_PROG3_2019_1_IMPBVY/MyDVDShop.Web/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyDVDShop.Web.Models
{
    public class Customer
    {
        [Display(Name = "Customer ID")]
        [Required]
        public int Customer_ID { get; set; }
        [Display(Name = "Customer Name")]
        [Required]
        public string Name { get; set; }
        [Display(Name = "Customer Address")]
        [Required]
        public string Address { get; set; }
        [Display(Name = "Customer E-mail")]
        [Required]
        public string E_mail { get; set; }
        [Display(Name = "Customer Age")]
        [Required]
        public int Age { get; set; }
        [Display(Name = "Customer Mobile")]
        [Required]
        public string Mobile { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_1_IMPBVY/MyDVDShop.Web/Models/CustomersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyDVDShop.Web.Models
{
    public class CustomersViewModel
    {
        public Customer EditedCustomer { get; set; }
        public List<Customer> ListOfCustomers { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_1_IMPBVY/MyDVDShop.Web/Controllers/CustomersController.cs
using AutoMapper;
using MyDVDShop.Data;
using MyDVDShop.Logic;
using MyDVDShop.Repository;
using MyDVDShop.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyDVDShop.Web.Controllers
{
    public class CustomersController : Controller
    {
        IMapper mapper;
        CustomersViewModel vm;
        IUgyfelLogic logic;

        //public CustomersController(ILogic<Ugyfel> logic, IMapper mapper)

        public CustomersController()
        {
            DVDShopDBContext db = new DVDShopDBContext();
            UgyfelRepository ugyfelRepository = new UgyfelRepository(db);
            logic = new UgyfelLogic(ugyfelRepository);
            mapper = MapperFactory.CreateMapper();

            vm = new CustomersViewModel();
            vm.EditedCustomer = new Customer();
            var ugyfels = logic.GetAllUgyfel();
            vm.ListOfCustomers = mapper.Map<IList<Data.Ugyfel>,List<Models.Customer>>(ugyfels);
        }

        private Customer GetCustomerModel(int id)
        {
            Ugyfel oneCustomer = logic.GetOneUgyfel(id);
            return mapper.Map<Data.Ugyfel, Models.Customer>(oneCustomer);
        }

        // GET: Customers
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("CustomerIndex",vm);
        }

        // GET: Customers/Details/5
        public ActionResult Details(int id)
        {
            return View("CustomerDetails", GetCustomerModel(id));
        }

        // GET: /Customers/Delete/5
        public ActionResult Delete(int id)
        {
            TempData["editResult"] = "Delete Failed";
            if (logic.Remove(id)) TempData["editResult"] = "Delete OK";
            return RedirectToAction(nameof(Index));
        }

        // GET: /Customers/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedCustomer = GetCustomerModel(id);
            return View("CustomerIndex", vm);
        }

        //POST: /Customer/Edit/ + Customer + editAction
        [HttpPost]
        public ActionResult Edit(Customer customer,string editAction)
        {
            if (ModelState.IsValid && customer != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    logic.AddUgyfel(customer.Name,customer.Address,customer.E_mail,customer.Age,customer.Mobile);
                }
                else
                {
                    bool success = logic.ChangeUgyfel(customer.Customer_ID,customer.Name, customer.Address, customer.E_mail, customer.Age, customer.Mobile);
                    if (!success) TempData["editResult"] = "Edit Failed";
                }
                return RedirectToAction(nameof(Index),vm);
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedCustomer = customer;
                return View("CustomerIndex", vm);
            }
        }




    }
}

CSHARP/OENIK_PROG3_2019_1_IMPBVY/MyDVDShop.Web/Views/Customers/CustomerDetails.cshtml
@model MyDVDShop.Web.Models.Customer
@{
    ViewBag.Title = "CustomerDetails";
}

<h2>Datasheet of one Customer</h2>

@Html.ActionLink("Back to the list", "Index");

<table border="1">
    <tr>
        <td>The ID for the customer</td>
        <td>@Model.Customer_ID</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Address)</td>
        <td>@Html.DisplayFor(m => m.Address)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.E_mail)</td>
        <td>@Html.DisplayFor(m => m.E_mail)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Age)</td>
        <td>@Html.DisplayFor(m => m.Age)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Mobile)</td>
        <td>@Html.DisplayFor(m => m.Mobile)</td>
    </tr>
</table>

CSHARP/OENIK_PROG3_2019_1_IMPBVY/MyDVDShop.Web/Views/Customers/CustomerEdit.cshtml
@model MyDVDShop.Web.Models.Customer

<h2>Edit one Customer</h2>

@using (Html.BeginForm("Edit", "Customers"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Customer_ID)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Age)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Age)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Address)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Address)</div>

    <div class="editor-label">@Html.LabelFor(m => m.E_mail)</div>
    <div class="editor-field">@Html.EditorFor(m => m.E_mail)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Mobile)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Mobile)</div>

    <input type="submit" value="SEND" />
}

CSHARP/OENIK_PROG3_2019_1_IMPBVY/MyDVDShop.Web/Views/Customers/CustomerIndex.cshtml
@model MyDVDShop.Web.Models.CustomersViewModel
@{
    ViewBag.Title = "CustomerIndex";
}

<h2>Customers Index</h2>

<p style="color:red; font-weight:bold">@TempData["editResult"]</p>

@Html.Partial("CustomerEdit",Model.EditedCustomer)

@Html.Partial("CustomerList",Model.ListOfCustomers)

CSHARP/OENIK_PROG3_2019_1_IMPBVY/MyDVDShop.Web/Views/Customers/CustomerList.cshtml
@model IEnumerable<MyDVDShop.Web.Models.Customer>

<h2>List of Customers</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>@Html.DisplayNameFor(m => m.First().Address)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
        <tr>
            <td>@Html.DisplayFor(m => item.Name)</td>
            <td>@Html.DisplayFor(m => item.Address)</td>
            <td>@Html.ActionLink("[Show]","Details", new { id = item.Customer_ID})</td>
            <td>@Html.ActionLink("[Del]", "Delete", new { id = item.Customer_ID }))</td>
            <td>@Html.ActionLink("[Edit]", "Edit", new { id = item.Customer_ID }))</td>
        </tr>
        }
    </table>
}